default_masterdata_update_check_timeout: 10    # 默认MasterData数据源检查更新超时时间（秒）
default_masterdata_download_timeout: 30       # 默认MasterData下载超时时间（秒）
default_rip_asset_download_timeout: 60         # 默认解包资源下载超时时间（秒）
rip_img_cache_max_res: 256*256                # 解包资源图片缓存最大分辨率
default_version_update_interval: 10 # 版本更新间隔
