jp:
  name: 日服  # 中文名
  timezone: Asia/Tokyo  # 时区
  enable: true  # 启用这个服务器
  options:
    - default # 默认服务器
    - need_translate # 需要翻译
    - fifth_anniversary # 已过五周年
    - mysekai # 允许烤森订阅
    - ad_result # 允许广告奖励
    - friend_code # 可以查询好友码
    - masterdata # 获取masterdata
    - asset # 获取asset
    - snowy # snowy 允许的服务器

cn:
  name: 国服 
  timezone: Asia/Shanghai
  enable: true
  options:
    # 关于这个local，可以直接用系统时区
    - local # 这个字段，用于指示本地时区，其它服务器的时间会被换算到本地时间
    - translated # 已翻译过
    - compact_data # 朝夕光年服的特殊设置
    - mysekai
    - bd_mysekai # 朝夕光年服不允许烤森
    - masterdata
    - asset
    - snowy # snowy 允许的服务器

tw:
  name: 台服
  timezone: Asia/Taipei
  enable: false # 为false，就禁用这个服务器
  options:
    - translated # 已翻译过
    - mysekai
    - bd_mysekai
    - compact_data

kr:
  name: 韩服
  timezone: Asia/Seoul
  enable: false # 为false，就禁用这个服务器
  options:
    - need_translate
    - mysekai
    - bd_mysekai
    - compact_data

en:
  name: 国际服
  timezone: America/Los_Angeles
  enable: false # 为false，就禁用这个服务器
  options:
    - need_translate
    - mysekai