sekairanking:
  base_url: https://sekaibangdan.exmeaning.com/api/v1
  token:
  cache_duration: 300
sekaiprofile:
  base_url: https://sekaiprofile.exmeaning.com/profile/{region}/{user_id}?token={token}
  token: